### PR TITLE
fix: removed unnecessary vehicles

### PR DESCRIPTION
**Pull request by GttMone**
## Description

Removed unnecessary vehicles in the `shared/vehicles.lua` module that don't exist in game build 3095 (in regards to pull [#102](https://github.com/Qbox-project/txAdminRecipe/pull/102))

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Comment by mafewtm** [comment]
The recipe will be moved back to 3258 or 3323 soon.

**Comment by GttMone** [comment]
This is so chaotic! Five days ago, you merge a pull request that changes the game build and now you're saying it's going to be reverted? I wasted all that time to update my server's game build + vehicles.lua file and now it's gonna be all for nothing.
I have no words...

**Comment by Manason** [comment]
> This is so chaotic! Five days ago, you merge a pull request that changes the game build and now you're saying it's going to be reverted? I wasted all that time to update my server's game build + vehicles.lua file and now it's gonna be all for nothing.
> 
> I have no words...

Maybe a better organization of the vehicles.lua would be groupings by game version rather than alphabetical. That would make it easier to add or remove a grouping for a specific version. We could even have logic at the top of the file which determines which vehicles end up in the returned table based on the game version.

**Comment by mafewtm** [comment]
> This is so chaotic! Five days ago, you merge a pull request that changes the game build and now you're saying it's going to be reverted? I wasted all that time to update my server's game build + vehicles.lua file and now it's gonna be all for nothing. I have no words...

Reverting the game build wasn't my idea. I didn't think it was really that necessary but here we are. As for wasting time, it does nothing to change a convar and you didn't really need to touch the vehicles.lua. Just dont use the vehicles from the update. Regardless of what happened, as manason said, adding additional logic is an option. I don't see why we need to overcomplicate the vehicles.lua but I guess we'll see what we do.

**Comment by D4isDAVID** [comment]
> I wasted all that time to update my server's game build + vehicles.lua file and now it's gonna be all for nothing.

Please, next time you make a change that takes a good amount of time, communicate with us and ask whether the change is needed.

We may still use information from this PR, so it might not be all for nothing, but it'd be nice if future cases of accidental time wasted will be prevented by communicating with us beforehand.

**Comment by GttMone** [comment]
Alright 👍

**Pull request closed without merging**
