### PR TITLE
feat: release and versioning automation

### PR DESCRIPTION
**Pull request by Manason**
## Description

- shamelessly stolen from ox
- can't be done centrally as the bundle steps reference files specific to this repository

### CODE REVIEW

**Comment by BerkieBb** [comment]
This can go into the github-docs repo, only thing you need to do then is include the repo name in the zip file instead of hardcoding

**Comment by Manason** [comment]
> This can go into the github-docs repo, only thing you need to do then is include the repo name in the zip file instead of hardcoding

The files would need to be passed then as well. Also if there are web files to build there's a bunch of additional steps to add.

**Comment by TheiLLeniumStudios** [comment]
As mentioned in discord, I'll setup a custom workflow that can be distributed across all repos and it will take care of the build steps if they are needed. So this can be closed

**Comment by Manason** [comment]
Will use this for now until Illenium finishes the global workflow

**Pull request merged**
