### PR TITLE
Adding a clear currency to the server

### PR DESCRIPTION
**Pull request by bicatcho11**
## Description

Adding a clear currency to the server
example $

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Comment by Manason** [comment]
Can you include within this same PR how the new config value will be used?

**Comment by bicatcho11** [comment]
If I want to change the server currency
Can I change it from one place?
Or do I go to each file one by one and change them?
@Manason

**Comment by Manason** [comment]
> If I want to change the server currency
> Can I change it from one place?
> Or do I go to each file one by one and change them?
> @Manason

I have no idea how you change the currency unit.

**Comment by bicatcho11** [comment]
More than one framworks works this way

**Pull request closed without merging**
