### PR TITLE
Replace QB items.lua and weapons.lua with Ox

### PR DESCRIPTION
**Pull request by Scullyy**
## Description
This replaces the QBCore items.lua and weapons.lua with the ox one, I also had to add a WeaponHashes table for reverse hashing since ox uses strings. I have open PR's on other resources to be compatible with this also.

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Review by Manason — CHANGES_REQUESTED** [review]
This is a breaking change. The data format of ox_inventory is not the same as shared/weapons.lua

**Review by TonybynMp4 — APPROVED** [review]
YES I LOVE YOU

**Comment by Scullyy** [comment]
The items.lua will need to replace the one inside ox_inventory with the recipe. If not using the oldItems method this may need it's own bridge inside ox_inventory.

**Comment by BerkieBb** [comment]
I am not sure about this, I would rather not have an items.lua anymore in the future as they all get picked up by ox_inventory and placed in the data/items.lua anyway, otherwise they don't work

**Comment by SKITTLE6969** [comment]
only issue that i see is when ox inventory try to convert the item lua in shared what happens then

**Pull request closed without merging**
