### PR TITLE
add middle name for character

### PR DESCRIPTION
**Pull request by bicatcho11**
## Description

add middle name for character

## Checklist

- [x] My pull request fits the contribution guidelines & code conventions.
- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.

### CODE REVIEW

**Comment by MafewTM** [comment]
I personally don't see any real use for this other than maybe for some sort of RP purpose. If we do support this, this should be a configurable option. Server owners should have the ability to enable or disable this field.

**Comment by Manason** [comment]
I think this will make things more complex then they need to be. A lot of scripts already assume the first name + last name combo, and if wanting a middle name for RP, one could add it to the list name already.

**Comment by bicatcho11** [comment]
> I personally don't see any real use for this other than maybe for some sort of RP purpose. If we do support this, this should be a configurable option. Server owners should have the ability to enable or disable this field.

```        {
            type = 'input',
            required = false,
            icon = 'user-pen',
            label = locale('info.middle_name'),
            placeholder = 'Middle'
        },```
        
        Is this good ?

**Comment by Manason** [comment]
This is a feature that would need greater discussion on if it's going to be done, and if so, how it would be done. Please open an issue if you want to suggest this.

**Pull request closed without merging**
