### PR TITLE
refactor: use lib.triggerClientEvent

### PR DESCRIPTION
**Pull request by solareon**
## Description

lib.triggerClientEvent offers improved performance for sending client events to multiple clients. This moves events sent to all clients to lib.triggerClientEvent

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Review by Manason — APPROVED** [review]
Is this a new lib feature? Do we need to increase the minimum ox_lib version required?

**Comment by solareon** [comment]
> Is this a new lib feature? Do we need to increase the minimum ox_lib version required?

Three months old. It's in 3.20.0 and later https://github.com/overextended/ox_lib/blob/master/imports/triggerClientEvent/server.lua

**Review by mafewtm — APPROVED** [review]
I think this should be tested before merging to make sure everything works with this

**Comment by FjamZoo** [comment]
real men test in prod

**Pull request merged**
